### ISSUE TITLE
Limestone + RVM

### ISSUE THREAD

**Issue by pouta** [archonic/limestone#23]
After running the following command:

```
docker-compose run web yarn install --pure-lockfile
```

I get the following error:

```
Step 7/15 : RUN bundle install
 ---> Running in 92d984434d85
Your Ruby version is 2.7.1, but your Gemfile specified 2.7
ERROR: Service 'web' failed to build: The command '/bin/sh -c bundle install' returned a non-zero code: 18
```

When checking my ruby version:

```
limestone · master ⟩ ruby -v
ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-darwin19]
```

I know I must be missing something obvious. But since this project uses docker, my local ruby version should not matter.

**Comment by archonic** [comment]
Correct, rvm is not relevant to this project when using docker. When you run `ruby -v`, that command is not running inside the web container. `docker-compose run web ruby -v` would `ruby -v` inside the web container.

That said, it seems there's a new default for ruby 2.7.1 in the image `ruby:2.7-alpine`. Try changing the first line of Dockerfile to `ruby:2.7.0-alpine` to be more specific.

**Comment by archonic** [comment]
@pouta If the above didn't work for you, feel free to reopen. I believe it would since it would pin the ruby version at 2.7.0.

**Comment by archonic** [comment]
@pouta Just an FYI, I've updated to 2.7.1 and now have the version pinned at that.
