### ISSUE TITLE
Issues with administrate assets

### ISSUE THREAD

**Issue by biximilien** [archonic/limestone#37]
Hi @archonic,

I'm experimenting with limestone to use in my latest venture and finding it pretty great so far!

I think your latest commits to the master branch may have introduced a bug with administrate assets, however my fork already has some diverging changes so maybe it's on my side.

I've added these lines to sprockets `manifest.js` to fix the issue.

```
//= link administrate/application.css
//= link administrate/application.js
```

**Comment by archonic** [comment]
Hi @biximilien, thanks for being my first sponsor! 😄

During the latest updates I noticed Sprockets 4.x causing issues and left it out. I didn't pin the upper version though so running `bundle update` would pull the problematic version. Thanks for finding the fix! It's now in the master branch and I've updated Administrate so it's no longer relying on my fork as well.

**Comment by biximilien** [comment]
@archonic thanks for the update ;)

Glad to sponsor interesting projects :D

**Comment by archonic** [comment]
Putting a fork in this!
