### ISSUE TITLE
Issues with Docker

### ISSUE THREAD

**Issue by duartemvix** [archonic/limestone#48]
Apparently I've been running into some trouble with Docker but I'm certain it's not that complicated. My experience would tell me this is just a conflict of ports between my own local machine and Docker's redis and postgres containers.

I'm pretty lost as to where I would even begin to change settings for which port to use on compose. I have to rebuild the bundle each time I try something new on a new configuration.

```ERROR: for squad_redis_1  Cannot start service redis: driver failed programming external connectivity on endpoint squad_redis_1 (c478b03bbdd6142824f4301b241c70a3c69fb9ccc6cca2c3dabf36315ed12a46): Error starting userland proxy: listen tcp4 0.0.0.0:6379: bind: address already in use```

```ERROR: for postgres  Cannot start service postgres: driver failed programming external connectivity on endpoint squad_postgres_1 (83ab1031e351424120617a313502a267523ee2a52d37ee29bde5bb5513fa5521): Error starting userland proxy: listen tcp4 0.0.0.0:5432: bind: address already in use```

**Comment by archonic** [comment]
That is indeed a conflict of the port in use on your machine. You could stop the process which is using port `6379` (most likely redis), or change the port. To change the port, edit this line:
https://github.com/archonic/limestone/blob/master/docker-compose.yml#L18

The format is `[host port]:[container port]`. You could just bump it by one for example to `6380:6380`.

Then change the `REDIS_BASE_URL` in the .env file to use that port. It's this line in the example file:
https://github.com/archonic/limestone/blob/master/.env-example#L91

**Comment by duartemvix** [comment]
> That is indeed a conflict of the port in use on your machine. You could stop the process which is using port `6379` (most likely redis), or change the port. To change the port, edit this line:
> https://github.com/archonic/limestone/blob/master/docker-compose.yml#L18
> 
> The format is `[host port]:[container port]`. You could just bump it by one for example to `6380:6380`.
> 
> Then change the `REDIS_BASE_URL` in the .env file to use that port. It's this line in the example file:
> https://github.com/archonic/limestone/blob/master/.env-example#L91
> 
> The same thing would need to be done for Postgres - either stop the localhost process or change ports for docker stuff.
> 
> Keep in mind that Docker is totally optional. You could use RVM + redis + postgres on your own machine and run Rails, Sidekiq, etc with foreman or run them in a new terminal tab.

I'm sorry for bringing Docker issues into here. I've been putting off learning about Docker for as long as 2 years already and I couldn't skip it further this time.

Apparently I got everything undercontrol and working. You might close this if you wish.

**Comment by archonic** [comment]
No worries! I'm here to help. Glad you got it working.

A typical production setup uses both nginx and puma. Nginx terminates the SSL certificate and routes traffic to one or more web pods running puma. At least that's the setup I've run on two environments and I hear it's common in other setups. I will eventually detail a production setup in a wiki article. I'll probably start by documenting a Heroku setup, then Dokku. Kubernetes + Helm is much harder to document.
