### ISSUE TITLE
Add documentation for `public_registration` feature in Flipper

### ISSUE THREAD

**Issue by aeksco** [archonic/limestone#6]
@archonic Love the project! Taking some time today to play around with it and I needed to do a bit of digging before I figured out I had to add the `public_registration` feature in Flipper - we should update `README.md` with some instructions so new Users can register for the site

**Comment by archonic** [comment]
Thanks! You're the first person to open an issue that isn't me so thanks for using it!

What would be added about flipper that isn't in the [Bonus Points](https://github.com/archonic/limestone#bonus-points) section? It could certainly have a better title.

**Comment by aeksco** [comment]
Sure thing, thanks again for building it! I actually missed the `Bonus Points` section - I'm more than happy to open a PR with some documentation updates to clarify some of the first-steps most devs would need to take to get up and running with `limestone` - LMK your thoughts!

**Comment by archonic** [comment]
Ya, please do write a PR with some clarifications!

**Comment by archonic** [comment]
Thanks again @aeksco.
