### ISSUE TITLE
Add note to README detailing Stripe API key requirement

### ISSUE THREAD

**Issue by aeksco** [archonic/limestone#8]
Realized after provisioning the Docker containers that you need to have `STRIPE_*` environment variables defined in order for the `docker-compose exec web rails db:setup` to succeed.

We should add a note to `README.md` detailing this requirement :+1:

**Comment by archonic** [comment]
Right, totally forgot about that. If you're prepping a PR to clear up first-time setup, could it include this?

**Comment by aeksco** [comment]
100%, more than happy to build out `README.md` a bit - might be nice to include some screenshots of the app as well so people can get a feel for what's at the end of the tunnel after registering for Stripe and whatnot
